title: "Alex Um"
author: "Alex Um"
description: "Alex's Personal Website"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  #- {file: "index.md", title: Home}
  - {url: "https://drive.google.com/file/d/1LFMlRMFU-Y97JY2BAFC4AyY7jvoJmOqG/view?usp=sharing", title: Resume}
  #- {file: "README.md", title: Alex}
  #- {url: "https://drive.google.com/drive/folders/1OBa0d3eBLdMFivzQ05zMrnG_cEp6GpR-?usp=drive_link", title: CSM Questions}

external:                  # shows a footer with social links - for available icons see 
  - {title: Mail, icon: envelope, url: "mailto:syeon.um@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/alexseungum"}
  - {title: Linkedin, icon: linkedin, url: "https://linkedin.com/in/alexseungum/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
